#!/usr/local/bin/python
'''
Copyright (C) 2013- Swedish Meteorological and Hydrological Institute (SMHI)

This file is part of RAVE.

RAVE is free software: you can redistribute it and/or modify
it under the terms of the GNU Lesser General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

RAVE is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public License
along with RAVE.  If not, see <http://www.gnu.org/licenses/>.
'''

## Running the hello tutorial PGF plugin.

## @file
## @author Daniel Michelson, SMHI
## @date 2013-11-18

import sys, os, xmlrpclib
from rave_defines import PGF_HOST, PGF_PORT


if __name__ == "__main__":
    here = os.getcwd()
    server = xmlrpclib.ServerProxy("http://%s:%i/RAVE" % (PGF_HOST, PGF_PORT))
    response = server.generate("eu.baltrad.beast.hello",
                               [os.path.join(here, sys.argv[1])], [])
